// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7A8hcjPS5vSZ-vjjySo_NiwSJQPQZjKg',
    appId: '1:784303908599:web:eca50413087eb50a47d5f2',
    messagingSenderId: '784303908599',
    projectId: 'saml-2a594',
    authDomain: 'saml-2a594.firebaseapp.com',
    storageBucket: 'saml-2a594.appspot.com',
    measurementId: 'G-FET1VQVHNQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4dldmMGemsXrCF4EPvXV4Fvm_PtRA-wE',
    appId: '1:784303908599:android:a87bdcabcc6288a547d5f2',
    messagingSenderId: '784303908599',
    projectId: 'saml-2a594',
    storageBucket: 'saml-2a594.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGP3LqdDACXdx1tsESZFS_JCmH6CDVG3s',
    appId: '1:784303908599:ios:d9392a9742ccb93047d5f2',
    messagingSenderId: '784303908599',
    projectId: 'saml-2a594',
    storageBucket: 'saml-2a594.appspot.com',
    iosBundleId: 'com.example.otpVerification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGP3LqdDACXdx1tsESZFS_JCmH6CDVG3s',
    appId: '1:784303908599:ios:d9392a9742ccb93047d5f2',
    messagingSenderId: '784303908599',
    projectId: 'saml-2a594',
    storageBucket: 'saml-2a594.appspot.com',
    iosBundleId: 'com.example.otpVerification',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7A8hcjPS5vSZ-vjjySo_NiwSJQPQZjKg',
    appId: '1:784303908599:web:3d3350c7fa01bc4f47d5f2',
    messagingSenderId: '784303908599',
    projectId: 'saml-2a594',
    authDomain: 'saml-2a594.firebaseapp.com',
    storageBucket: 'saml-2a594.appspot.com',
    measurementId: 'G-YG12BBRXSX',
  );
}
